version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eazipurse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eazipurse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgadmin_data: 