version: '3.8'

services:
  backend:
    build:
      context: ./WalletAppInDjango
      dockerfile: Dockerfile
    container_name: eazipurse_backend
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=eaziPurse.settings
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PAYSTACK_KEY=${PAYSTACK_KEY}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - PAYSTACK_CALLBACK_URL=${PAYSTACK_CALLBACK_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - ./WalletAppInDjango:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    networks:
      - eazipurse_network
    restart: unless-stopped

  frontend:
    build:
      context: ./eazi-purse-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: eazipurse_frontend
    ports:
      - "5173:5173"
    networks:
      - eazipurse_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  eazipurse_network:
    driver: bridge
