# Generated by Django 5.2.4 on 2025-08-04 11:14

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_transaction_reference_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=wallet.models.generate_reference, max_length=40, unique=True),
        ),
    ]
