# Generated by Django 5.2.4 on 2025-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
