# Generated by Django 5.2.4 on 2025-08-01 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('platform_version', models.CharField(default='v1.0.0', max_length=20)),
                ('database', models.CharField(default='PostgreSQL', max_length=50)),
                ('system_status', models.CharField(default='Healthy', max_length=20)),
                ('uptime', models.CharField(default='99.9%', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
